name: sparingin
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  shared_preferences: ^0.5.4
  carousel_slider: ^1.3.0
  smooth_star_rating: ^1.0.3
  toast: ^0.1.5
  flutter_verification_code_input:
      git:
        url: git://github.com/awaik/flutter_verification_code_input.git
  datetime_picker_formfield: ^0.4.3
  intl: ^0.15.8
  sms: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/lapangan.jpg
    - assets/images/lapangan2.jpg
    - assets/images/turnamen1.jpg
    - assets/images/turnamen2.jpg
    - assets/images/icon.png
    - assets/images/sparingin.png
    - assets/images/icons/akunSaya.png
    - assets/images/icons/cariLapangan.png
    - assets/images/icons/cariLawan.png
    - assets/images/icons/faq.png
    - assets/images/icons/pengaturan.png
    - assets/images/icons/timKami.png
    - assets/images/profile.png
    - assets/images/card/chelsea.png
    - assets/images/card/chelseaFutsal.jpg
    - assets/images/card/liverpool.png
    - assets/images/card/liverpoolFutsal.jpg
    - assets/images/card/totenham.png
    - assets/images/card/totenhamFutsal.jpg
    - assets/images/card/juaraFutsal.jpg
    - assets/images/card/krustykrab.png
    - assets/images/card/phuketUnitedFutsal.jpg
    - assets/images/card/phuketUnited.png
    - assets/images/card/canadianFutsal.jpg
    - assets/images/card/canadian.png
    - assets/images/card/its.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"